# Generated by Django 4.2 on 2023-04-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stp_resources', '0003_rename_question_question_resources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='resources',
        ),
        migrations.AddField(
            model_name='question',
            name='resources',
            field=models.ManyToManyField(to='stp_resources.webresource'),
        ),
    ]
