# Generated by Django 4.2 on 2023-04-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stp_resources', '0005_remove_question_resources_question_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='resources',
        ),
        migrations.AddField(
            model_name='webresource',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stp_resources.question'),
        ),
    ]
